### ISSUE TITLE
Re-format JSON output

### ISSUE THREAD

**Issue by philhagen** [EricZimmerman/PECmd#2]
Would be more straightforward and much faster to handle single JSON output file with only the fields consistent with CSV output.  Similar streamlining to what was adjusted with the MFTECmd and LECmd tools.

**Comment by EricZimmerman** [comment]
sample files sent. please let me know

**Comment by EricZimmerman** [comment]
oops. this is pecmd. will look

**Comment by EricZimmerman** [comment]
sample file sent

one file, based on csv object, ISO8601 timestamps

**Comment by EricZimmerman** [comment]
this is done. pushed as 1.3.3. please take a look and we can tweak as needed
