### ISSUE TITLE
Date stamps not ISO8601

### ISSUE THREAD

**Issue by philhagen** [EricZimmerman/PECmd#4]
date stamps reflect a partial timestamp, e.g. `2019-05-17 13:55:06`

to match other tools and remove time zone ambiguity, all should be iSO8601, e.g. `2019-05-17T13:55:06.415196+00:00`

**Comment by philhagen** [comment]
BTW, this was verified against v1.3.4.0

**Comment by EricZimmerman** [comment]
fixed.

didnt bump version, but if you use PS script you will get the change

{
  "SourceFilename": "C:\\Windows\\Prefetch\\ARSENALIMAGEMOUNTER.EXE-E01223FF.pf",
  "SourceCreated": "2019-05-22T15:50:18.7075580+00:00",
  "SourceModified": "2019-06-09T22:09:12.6435851+00:00",
  "SourceAccessed": "2019-06-09T22:09:12.6435851+00:00",
  "ExecutableName": "ARSENALIMAGEMOUNTER.EXE",
  "Hash": "E01223FF",
  "Size": "264852",
  "Version": "Windows 10",
  "RunCount": "3",
  "LastRun": "2019-06-09T22:09:02.6274027+00:00",
  "PreviousRun0": "2019-05-24T19:00:03.6469747+00:00",
  "PreviousRun1": "2019-05-22T15:50:08.6968471+00:00",
  "Volume0Name": "\\VOLUME{01d36f5b14d78b2e-d014e38f}",
  "Volume0Serial": "D014E38F",
  "Volume0Created": "2017-12-07T12:58:30.6253614+00:00",
  "Volume1Name": "\\VOLUME{01d49676f048bd4c-c4f05692}",
  "Volume1Serial": "C4F05692",
  "Volume1Created": "2018-12-18T02:11:08.2193228+00:00",
  "Directories": ""\\WINDOWS\\MICROSOFT.NET\\ASSEMBLY\\GAC_MSIL\\MICROSOFT.VISUALBASIC\\V4.0_10.0.0.0__B03F5F7F11D50A3A",
  "FilesLoaded": "\\VOLUME{01d49676f048bd4c-c4f05692}\\WINDOWS\\SYSTEM32\\NTDLL.DLL, \\VOLUME{01d36f5b14d78b2e-d014e38f}\\S",
  "ParsingError": false
}
