### ISSUE TITLE
Created and modified times

### ISSUE THREAD

**Issue by jrobm2k9** [EricZimmerman/PECmd#6]
When I run PECmd.exe on a single file and output to the terminal, the "Created on" time listed is 7 hours past the "Date Created" time listed in the file explorer, and the "Modified on" time is 8 hours past the Date Modified time in the file explorer.

The minutes and seconds are correct, and the date is correct as long as you add the 7 or 8 hours depending on what you're looking at.  

My question is, does the PECmd.exe use a different time zone?  Or does it go off of a time other than what the file explorer uses?

**Comment by EricZimmerman** [comment]
it should always be UTC.

can you share a screenshot?

are you not seeing that?

**Comment by jrobm2k9** [comment]
![pecmd](https://user-images.githubusercontent.com/16310787/68610585-b3ab6a00-047d-11ea-994a-31170f3ad3a3.PNG)

No, I believe the time is off by a couple of hours, are you able to see the screen shot?

**Comment by EricZimmerman** [comment]
looks fine. what is the issue?

what timezone are you in, and what do you think the times should be? are those times NOT UTC vs your time zone?

**Comment by EricZimmerman** [comment]
my guess is you are in a timezone that honors daylight savings time and are seeing things shift over the fall back date

**Comment by jrobm2k9** [comment]
Yea, I'm in chicago, the times in that screenshot are incorrect so I ran it again but it is still 7 hours off on the "created on" time which could be caused the daylight savings time, but the "modified time" is 8 hours off?

In this screenshot I moved the date created and date modified columns in the file explorer.


![pecmd](https://user-images.githubusercontent.com/16310787/68611759-77c5d400-0480-11ea-91fe-7cd39329cb7d.PNG)

**Comment by jrobm2k9** [comment]
Ignore that last comment, i'm an idiot, thanks for responding, love the tool!

**Comment by EricZimmerman** [comment]
ok so all is well? closing, but lemme know if not
