### ISSUE TITLE
Getting an error 87 with a build from the current master 

### ISSUE THREAD

**Issue by smclinden** [EricZimmerman/PECmd#7]
This is on a Windows 10 system compiled with VS2019.

PECmd version 1.4.0.0

Author: Eric Zimmerman (saericzimmerman@gmail.com)
https://github.com/EricZimmerman/PECmd

Command line: -d D:\ExchangeServerBoot\Prefetch\

Keywords: temp, tmp

Looking for prefetch files in 'D:\ExchangeServerBoot\Prefetch\'

Error getting prefetch files in 'D:\ExchangeServerBoot\Prefetch\'. Error: (87) The parameter is incorrect: [D:\ExchangeServerBoot\Prefetch\LMI_RESCUE.EXE-001B210A.pf]

**Comment by EricZimmerman** [comment]
thats a random one i see from time to time. remove the \ on the directory perhaps, or try copying the pf files to a different directory. 

try that and let me know

**Comment by smclinden** [comment]
Sorry. It didn't change anything.

**Comment by EricZimmerman** [comment]
if you copy files, or use -f, does it work as expected against single files?

**Comment by EricZimmerman** [comment]
this may also be corruption, and nothing to do with the tool.

https://answers.microsoft.com/en-us/windows/forum/windows8_1-performance/error-87-parameter-is-incorrect/2d481b5e-11e5-4bfa-b0cc-f771f3a6cb3c

**Comment by smclinden** [comment]
For many of the files, yes, it works with -f.

But for those in which I have the greatest interest, I get:

PS D:\ExchangeServerBoot\Prefetch> C:\cygwin64\usr\src\PECmd\PECmd\bin\Debug\PECmd.exe -f .\SVAC5F~1.PF
PECmd version 1.4.0.0

Author: Eric Zimmerman (saericzimmerman@gmail.com)
https://github.com/EricZimmerman/PECmd

Command line: -f .\SVAC5F~1.PF

Keywords: temp, tmp

Processing '.\SVAC5F~1.PF'

Error opening '.\SVAC5F~1.PF'. Message: Index and count must refer to a location within the buffer.
Parameter name: bytes

**Comment by EricZimmerman** [comment]
then that file is corrupt most likely. look at them in a hex editor

why are you running it out of cygwin? are these binaries you built,. or mine?

**Comment by smclinden** [comment]
I'm not running it out of cygwin. It is being run from Windows Terminal (Powershell). I just happened to put the source in the cygwin space but it was compiled for Windows using VS2019.

But, in this case, I should have looked a little harder. All of the files with random names, eg "RUxxxx~.pf" were 0 bytes.

**Comment by EricZimmerman** [comment]
ah well i should adda check for 0 byte files.

while compiling things on your own is fine, you can get signed binaries from me as well on my download site
