### ISSUE TITLE
Issue with CSV output

### ISSUE THREAD

**Issue by edenn-cyrebro** [EricZimmerman/PECmd#8]
Hi,
Just wanted to say I have been using your tools for a long time and all of them are great.
However, I've been having some issues with PECmd CSV output.
It seems that the loaded DLL list sometimes corrupts the CSV structure:
![image](https://user-images.githubusercontent.com/74725705/117649470-3a86f300-b198-11eb-9420-9d1b5b47f7d4.png)

Hope this helps improve your code!
I'm sorry that I cannot upload the full output.

**Comment by EricZimmerman** [comment]
i cant help you if i cant see what is wrong.

load the data into TLE (your image looks like excel). 

is this a CSV issue, or is it an issue with whatever you are using to view your CSVs?

feel free to share the file, or at least the row with an issue, but without more concrete example (and ideally, the .pf file itself) i cannot do much here

**Comment by edenn-cyrebro** [comment]
Thanks for the quick reply!
I am viewing this through excel.
Is it possible to send the PF file to you privately?
In any case, in the image you can see that the DLL list from the second line invades the third line and every comma is interpreted as a new column.

**Comment by EricZimmerman** [comment]
Use timeline Explorer. 

You can always email me the file but this is most likely an excel issue.
